export const ticketTypes = new Map([
    ["sixtyDayAb", "Special Senior Citizen Day Ticket AB"],
    ["sixtyWeekAb", "Special Senior Citizen Weekly Ticket AB"],
    ["sixtyMonthAb", "Special Senior Citizen Monthly Ticket AB"],
    ["sixtyDayAbc", "Special Senior Citizen Day Ticket ABC"],
    ["sixtyWeekAbc", "Special Senior Citizen Weekly Ticket ABC"],
    ["sixtyMonthAbc", "Special Senior Citizen Monthly Ticket ABC"],
    ["sixtyDayBc", "Special Senior Citizen Day Ticket BC"],
    ["sixtyWeekBc", "Special Senior Citizen Weekly Ticket BC"],
    ["sixtyMonthBc", "Special Senior Citizen Monthly Ticket BC"],
    ["ChildDay", "Reduced Fare Day Ticket(Age 6 - 14)"],
    ["childWeek", "Reduced Fare Weekly Ticket(Age 6 - 14)"],
    ["childMonth", "Reduced Fare Monthly Ticket(Age 6 - 14)"],
    ["dayAbc", "Day Ticket ABC"],
    ["dayBc", "Day Ticket BC"],
    ["dayAb", "Day Ticket AB"],
    ["monthAbc", "Monthly Ticket ABC"],
    ["monthBc","Monthly Ticket BC"],
    ["monthAb","Monthly Ticket AB"],
    ["weekAbc","Weekly Ticket ABC"],
    ["weekBc","Weekly Ticket BC"],
    ["weekAb","Weekly Ticket AB"],
    ["group","Group Day Ticket(Upto 12 people)"],
    ["smallGroup", "Small Group Day Ticket(Upto 6 people)"]
  ]);